### ISSUE TITLE
Mobile: logo and menu icon should be on same row

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-reykjavik#57]
![screen shot 2016-01-21 at 13 14 28](https://cloud.githubusercontent.com/assets/13623224/12479014/20540462-c041-11e5-9796-495c3fcd3d32.png)

**Comment by kaspar-naaber** [comment]
There's no good method to fix that. Menu button is aligned with header title text. If we prefer image then the title text is misaligned.

I'll mark it as a wontfix at the moment.
