### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-reykjavik#59]

**Comment by SSirjes** [comment]
_I round testing (23.05.16)_

* [ ] **Content - Link has too many borders**

![screen_shot_2016-05-23_at_16_10_36](https://cloud.githubusercontent.com/assets/13623224/15471986/7d040a06-2101-11e6-911c-f695697f64da.jpg)

**Comment by SSirjes** [comment]
* [ ] **Button hover is missing**

**Comment by SSirjes** [comment]
* [ ] **Custom and form button Background color are displayed different**

![screen shot 2016-05-25 at 10 35 28](https://cloud.githubusercontent.com/assets/13623224/15531736/90434370-2264-11e6-80d5-d0812edfd954.png)
